### ISSUE TITLE
Callback on listening?

### ISSUE THREAD

**Issue by fcosrno** [muit/serveMe#3]
Is there a way to invoke a function when server is listening, like this?

```javascript
    var serveMe = ServeMe();
    serveMe.start(3333,function(){
        console.log("server started");
    });
```

The documentation lists events, but listening is not one of them. Thanks!

**Comment by muit** [comment]
Forgot to implement that :P Done.
Thanks for helping.

**Comment by fcosrno** [comment]
You're welcome, but thanks go to you! :)
