### ISSUE TITLE
Can't serve files with spaces

### ISSUE THREAD

**Issue by ptelad** [muit/serveMe#8]
Hi guys,
I've encountered an issue with files having spaces in their name not being found.
This is because the browser will send a GET request with %20 instead of the spaces so the file's path gets messed up.

The solution is simple,
Please review it on my fork:
https://github.com/ptelad/serveMe/commit/2ee30dee2471e980d37e910351fa4ca5ff338f4a

Or maybe you have a better solution, I admit this is quick fix that might be done better.

Thank you!

**Comment by muit** [comment]
Sorry for the delayed answer, @ptelad 

You are right, that's a bug I didn't encounter. 
Could you make a Pull Request with it?

Thanks to you!
